version: "3.5"

services:
#Mysql Container
  mysql:
    container_name: glpi_db
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi

#GLPI Container
  glpi:
    container_name: glpi
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "8030:80"